REMOVE_TF1_M6_NON_MOVIES =['CAUCHEMAR EN CUISINE', 'BONJOUR LA MATINALE TF1', 'QUI VEUT ETRE MON ASSOCIE', 'THE VOICE LA PLUS BELLE VOIX', 
                           'DANSE AVEC LES STARS', 'RECHERCHE APPARTEMENT OU MAISON', '66 MINUTES', 'ABSOLUMENT STARS', 'VENDREDI TOUT EST PERMIS AVEC ARTHUR',
                           '30 ANS D EMISSIONS CULTES', 'THE ISLAND L ILE DU BAGNE', 'L AMOUR EST DANS LE PRE', 'LA MEILLEURE BOULANGERIE DE FRANCE',
                           'STAR ACADEMY', '50 MN INSIDE', 'APPART', 'CAMPING PARADIS', 'JOSEPHINE', 'SCENES DE MENAGES', 'BETISIER', 'MASK SINGER', 'INCROYABLE TALENT',
                           'KOH LANTA', 'LES 12 COUPS DE MIDI', 'SOIREE SPECIALE', 'APPEL A TEMOINS', 'PEKIN EXPRESS', 'LE GOLDEN BACHELOR', 'L ILE DE LA TENTATION',
                           'NINJA WARRIOR']